### ISSUE TITLE
`DTXcodeBuild` is the wrong value to use

### ISSUE THREAD

**Issue by davedelong** [brycebostwick/XcodePluginLoader#1]
👋 Just watched your video on modding Xcode, where you talk about using `DTXcodeBuild` for determining plugin compatibility.

`DTXcodeBuild` does not describe the build version of that Xcode. It describes the version of Xcode used to *compile* that app. All compiled applications have a `DTXcodeBuild` value in their Info.plist.

If you want Xcode's actual build value, that's in its `Contents/version.plist` under the `ProductBuildVersion` key. (This explains the discrepancy between the value in the Info.plist and the value on xcodereleases.com)

**Comment by davedelong** [comment]
Hopper seems to think you can get this value from `-[NSProcessInfo xcodeProductBuildVersion]`, courtesy the `DevToolsSupport` framework.

**Comment by brycebostwick** [comment]
🤦 Hi Dave! Thanks for reporting this, I should have recognized the key — serves me right for rushing to support Xcode 15.3 midway through this project.

Just added #2 to support `ProductBuildVersion`. Great tip on `xcodeProductBuildVersion` too — thanks for digging it up! Appreciate both the initial report and direction — thank you again!
